
CREATE TABLE [dbo].[Phien](
	[Name] [nvarchar](250) NOT NULL,
	[CreateUser] [nvarchar](50) NULL,
 CONSTRAINT [PK_Phien] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


