//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KV2Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doi
    {
        public int Id { get; set; }
        public string Hohieu { get; set; }
        public string Huongdo { get; set; }
        public string Mangdai { get; set; }
        public string Giong { get; set; }
        public string Ghichu { get; set; }
        public string Diaban { get; set; }
        public Nullable<int> PhienId { get; set; }
    }
}
