//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KV2Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KV2FilterEntities : DbContext
    {
        public KV2FilterEntities()
            : base("name=KV2FilterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chinh> Chinhs { get; set; }
        public virtual DbSet<Doi> Dois { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Phien> Phiens { get; set; }
    }
}
